### ISSUE TITLE
关于最新版本实现的问题

### ISSUE THREAD

**Issue by yelantf** [A-Miracle/QiangHongBao#1]
你好，请问最新的版本你是如何实现的。我最近在调试时在开红包界面发现getRootInActiveWindow无法获得正确的节点，在它的节点下无法捕获“開”的Button。不知道你是如何实现的，如果不介意的话能否指点一下。（微信的版本是最新的6.5.13）

**Comment by A-Miracle** [comment]
使用Android Device Monitor连接手机, 通过Dump View Hierarchy for UI Automator找到Button“開”的Id. 最新版微信控件Id有所调整

**Comment by yelantf** [comment]
额，是这样的。我在点开某个红包之后但未点击button之前，利用getRootInActiveWindow获取了根节点，但是我遍历这个根节点的所有子节点并没有发现button控件（我是利用classname判断的）

**Comment by A-Miracle** [comment]
或许你 getRootInActiveWindow 调用早了, 页面还没加载完成, 捕获的窗口不对
